apiVersion: 1

datasources:
  - name: InfluxDB - WeatherFlow
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: weatherflow
      defaultBucket: weatherflow
      tlsSkipVerify: true
    secureJsonData:
      token: weatherflow-super-secret-token
    uid: data_source_influxdb
    isDefault: true
    editable: true

