name: Build Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
    contents: read
    packages: write


jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set the Docker image version
      - name: Set docker version
        id: vars
        run: |
          VERSION=$(git rev-parse --short HEAD)
          [[ "${{ github.ref_type }}" == "tag" ]] && \
            VERSION=v$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,;s/^v//')
          [[ "${{ github.ref }}" == "refs/heads/main" && \
             "${{ github.ref_type }}" == "push" ]] && VERSION=latest
          echo "version=${VERSION:-latest}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to Github Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max